find_library(N2K_LIB NAMES nmea2000)
find_path(N2K_INCLUDE "N2kMessages.h" DOC "The path to the N2K decoder library" HINTS /usr/local/include/nmea2000)
if(N2K_INCLUDE)
	include_directories(${N2K_INCLUDE})
	status("N2K include: " ${N2K_INCLUDE})
	status("N2K library: " ${N2K_LIB})
else()
	message(FATAL_ERROR "N2K Decoder library not found")
endif()
set(LIBS ${LIBS} ${N2K_LIB})

if(MSVC)
   add_definitions( -DBOOST_ALL_NO_LIB )
   add_definitions( -DBOOST_ALL_DYN_LINK )
endif()
set(BOOST_COMPONENTS program_options) 
if(MSVC)
    set(Boost_USE_MULTITHREADED   ON)
    set(Boost_USE_STATIC_LIBS     OFF)
    set(Boost_USE_STATIC_RUNTIME  OFF)
endif()
find_package(Boost 1.51 COMPONENTS ${BOOST_COMPONENTS} REQUIRED)
if(MINGW)
    # mingw-gcc fails to link boost::thread
    add_definitions(-DBOOST_THREAD_USE_LIB)
endif(MINGW)
set(LIBS ${LIBS} ${Boost_LIBRARIES})
include_directories(${Boost_INCLUDE_DIRS})
