//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// https://embedXcode.weebly.com
//
// Project 		NMEATalker
//
// Created by 	Brian Calder, 2020-06-09 11:31
//              CCOM/JHC
//
// Copyright 	© Brian Calder, 2020
// Licence 		BSD 3-term
//
// See 			NMEATalker.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN NMEATalker.ino
// ----------------------------------
//
// Last update: Jun 30, 2017 release 7.5.0

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
// Minimal proxy main() to be updated at build
#include "Arduino.h"

int main(void)
{
    setup();

    for (;;)
    {
        loop();
    }

    return 0;
}

// Sketch
#include "NMEATalker.ino"


#endif                                                                          // end embedXcode

