version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - manager.env
    environment:
      MANAGER_DATABASE_URI: ${MANAGER_DATABASE_URI}
    ports:
      - '8000:8000'
    volumes:
      - 'dbdata:/var/wibl'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/heartbeat"]
      interval: 10s
      timeout: 1s
      retries: 5
    command: 'gunicorn wibl_manager.application:app --workers 1 --bind 0.0.0.0:8000 --access-logfile -'
volumes:
  dbdata:
